# Generated by Django 5.1.4 on 2025-01-18 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_1508e0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-applied_at'], name='application_applied_d0ec77_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user'], name='application_user_id_9457c8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['opportunity'], name='application_opportu_e20f19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'opportunity')},
        ),
    ]
